### ISSUE TITLE
useContext() issue

### ISSUE THREAD

**Issue by apollyon12** [apollyon12/ReactHook#1]
I can't understand the useContext() usage of ComboB and ComboC.
Anyone please help me.

**Comment by michaelaltao** [comment]
When I started working with React.js, I also couldn't understand the usage of useContext() API clearly.
But after reading this article, I have a good sense of useContext() API. Hope to be helpful for you.
https://medium.com/technofunnel/usecontext-in-react-hooks-aa9a60b8a461

**Comment by apollyon12** [comment]
I see.
Thanks.
